### ISSUE TITLE
Push a tag :4 that points to latest minor/patch release (e.g. 4.1.1)

### ISSUE THREAD

**Issue by bradjones1** [emgag/docker-varnish#13]
The readme implies that there's a tag `4`, but it's gone from Docker Hub. Thanks for the work on this!

**Comment by Wohlie** [comment]
Same problem with tag 5.2, `emgag/varnish:5.2` it's not working anymore

**Comment by maetthu** [comment]
The problem with MAJOR- and MAJOR.MINOR tags is that you have to be at least somewhat sure you stay compatible with previous releases, but that's pretty difficult to maintain in this case because the shipped vmods are either third-party or somewhat on-and-off maintained by varnish. That's why I stopped pushing those tags about 9 months ago (6d5ec09e2e7384102343d602f97d8a6648bb5d75) because I had to remove the geoip due to maxmind retiring their legacy database format and the module itself not being maintained anymore... just tagging new versions with the same tag but without the module wouldn't have been ideal either - I figured that enough time has passed since then to finally cleanup the repo and remove any inconsistencies and confusions by having those unmaintained tags lying around.

I'm sorry this lead to breaks. In case of 4.1, you can directly use emgag/varnish:4.1.11, since it's EOL this won't receive any updates anyway. I pushed emgag/varnish:5.2.1 again as well, but you have to provide your own geoip database since the update mechanism is broken for quite a while now and it was also removed from debian-contrib as a package.

Be aware that both are EOL (4.1 since March this year, 5.2 has been retired mid 2018)  and won't receive any updates anymore, neither from varnish upstream nor from this repo. I strongly encourage you to update to a recent version.

**Comment by Wohlie** [comment]
Thank you for your quick and detailed response. We currently depend on a application which lack offical support of the newest varnish version.

Build works now with the image `emgag/varnish:5.2.1`.

Thank you!

**Comment by maetthu** [comment]
@Wohlie I'm glad this worked out for you. 

I've updated the legacy 4.1 branch with working builds for all old releases (4.1, 5.0, 5.1 and 5.2) and added some notes about the supported tags. Hope this clears it up for you all. I will keep those images around, although as noted, they won't be maintained.
