### ISSUE TITLE
log to stdout

### ISSUE THREAD

**Issue by Raboo** [emgag/docker-varnish#16]
Hi

I have a feature wish.
It would be awesome if this container would log to stdout(/dev/fd/1 or /dev/stdout) via varnishncsa or varnishlog.
Thus enabling "docker logs".

**Comment by maetthu** [comment]
Thank you for your input, but this would be outside the scope of this image. You can run varnishlog, varnishncsa or any other varnish cli tool as adhoc commands inside the running container if you need to hook into a running varnish process, but starting it by default alongside varnishd would require us to run a process manager like supervisord and add additional options to customize log output, especially for varnishlog since this is almost unusable without filtering on a busy instance. However, I'd like keep this image as simple as possible - just barebone varnishd, one process. It's pretty trivial to extend this image though, just override RUN with your supervisord startup command and run additional varnish tools in addition to init.sh.

**Comment by Raboo** [comment]
Ok, thank you for the details.
Maybe this can be solved via a side cart container? I might look into that.

**Comment by maetthu** [comment]
Assuming you are talking about Kubernetes, a sidecar container would probably work, since containers in a pod share the same namespace. But it needs some tinkering since most varnish tools need access to the shared memory file where varnish logs its status, which is stored in _/usr/local/var/varnish/SERVERNAME_ in this image. Setting the server name using something like `VARNISH_DAEMON_OPTS="-n xxx"` to make the directory name static instead of using the hostname of the container and sharing the _/usr/local/var/varnish/xxx_ directory between containers might be enough, but this is untested, never tried it myself.
