### ISSUE TITLE
Build multi-architecture Varnish images?

### ISSUE THREAD

**Issue by danielcompton** [emgag/docker-varnish#20]
I've recently bought an M1 Mac and found that it doesn't run x86 Varnish Docker images, seemingly due to the VCL compilation phase.

I was able to build a partially working Docker image from this repo just by running `docker build` on my M1 Mac. I didn't fully test all the features, but I was able to start it after commenting out `import dynamic;`.

```vcl
vcl 4.0;

import cookie;
import digest;
import directors;
# import dynamic;
import header;
import saintmode;
import purge;
import querystring;
import std;
import tcp;
import var;
import vsthrottle;
import xkey;

backend default {
    .host = "127.0.0.1";
    .port = "8080";
}

sub vcl_recv {
    std.log("you can't stop the signal!");
}
```

Would you be interested in building multi-architecture Varnish images? I _think_ that https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/ shows the current easiest way to do this with [buildx](https://github.com/docker/buildx), but I'm not too sure.

**Comment by maetthu** [comment]
Nice, thank you for your work :slightly_smiling_face:  I never built multi-arch images yet, but it would certainly be useful, especially since arm64 gains traction in the cloud space and the change to the build workflow looks simple enough to not be a hassle for future updates. I'll look into soon(ish).

Re vmod-dynamic: I haven't updated the module version in the Dockerfile for a while and back then when I built it, there hasn't been a dedicated branch for v6.6, so maybe this is already fixed upstream. Would you mind checking out if switching to the 6.6 branch and commit 1bf8f07e1e406501e800c89f99d2811191f9596f (https://github.com/nigoroll/libvmod-dynamic/tree/6.6) here https://github.com/emgag/docker-varnish/blob/master/6.6/Dockerfile#L68-L69 fixes it? I don't have arm64-v8 hardware available to test unfortunately.

**Comment by maetthu** [comment]
I have merged your changes. However, there isn't a specific build target for ARM v8, only supported platforms are:

* linux/amd64
* linux/arm64
* linux/riscv64
* linux/ppc64le
* linux/s390x
* linux/386
* linux/arm/v7
* linux/arm/v6

... so I just added builds for amd64 and arm64.

**Comment by danielcompton** [comment]
Thanks! Sorry for the delay, I’ll test the new builds out soon.
